import type { NextPage } from 'next'
import Head from 'next/head'
import { Category } from '../features/category'
import { PostDetailPage } from '../features/posts'

const category: Category = {
  id: 1,
  slug: 'engineer',
  name: 'エンジニア',
  iconName: 'FaCode',
  to: '/category/engineer',
}

const post = {
  id: 1,
  slug: 'first',
  title: '初投稿です',
  text: 'これは初登校の文章なり〜。これは初登校の文章なり〜。これは初登校の文章なり〜。これは初登校の文章なり〜。これは初登校の文章なり〜。これは初登校の文章なり〜。これは初登校の文章なり〜。これは初登校の文章なり〜。',
  imagePath: '/dummy.png',
  category,
  tags: [{ id: 1, slug: 'blog', name: 'ブログ', to: '/tag/blog' }],
  publishedDate: '2022-06-15',
  timeToRead: 3,
}

const Post: NextPage = () => {
  return (
    <>
      <Head>
        <title>Post Detail Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <PostDetailPage post={post} />
    </>
  )
}

export default Post
