import type { NextPage } from 'next'
import Head from 'next/head'
import { HomePage } from '../features/home'

const IndexPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HomePage />
    </>
  )
}

export default IndexPage
